```mermaid
flowchart TB
    subgraph Leadership
        Patrice_Barbedette["Patrice Barbedette<br/>CEO & President "]
        Evan_Carlson["Evan Carlson<br/>Chief Operating Officer "]
        Chris_Holt["Chris Holt<br/>Revenue Operations ✓"]
        Alexander["Alexander<br/>External Consultant / AI Project Manager 📧"]
    end
    subgraph Engineering
        Ludovic["Ludovic<br/>CTO 📧"]
        Loic["Loic<br/>Engineering Leadership 📧"]
    end
    subgraph Lemlist
        Tim_Brouillard["Tim Brouillard<br/>VP Business Development "]
        Cédric_Cibot-Voisin["Cédric Cibot-Voisin<br/>France Sales Manager "]
        Raphael_Hugnet["Raphael Hugnet<br/>BDR Lead - France "]
        Ismael_Sabbagh["Ismael Sabbagh<br/>BDR Lead - Spain 📧"]
        Sean_Herbert["Sean Herbert<br/>BDR Lead - UK ✓"]
        Stefano["Stefano<br/>BDR Lead - Italy 📧"]
        Christopher_T._Kuhn["Christopher T. Kuhn<br/>COO OTRS AG 📧"]
        Seima_Ishaq["Seima Ishaq<br/>BDR (OTRS) ✓"]
    end
    subgraph Loopio
        Dalila_Souiah["Dalila Souiah<br/>Global Presales Lead ✓"]
        Yann_Mercier["Yann Mercier<br/>Global Head / Product Owner, Loopio ✓"]
        Rod["Rod<br/>US Sales 📧"]
    end
    subgraph Other
        Laure_Ruperas["Laure Ruperas<br/>TBD "]
    end
```